// The words the glasses say, in the three languages lo is read in.
//
// Lifted key for key out of lo/src/i18n so that a heading on the glasses is the
// same heading as on the phone — "Nearby posts" is not re-invented here as
// "Posts near you", and 警報・注意報 is what the warnings card is called on both
// screens. Only the keys that actually reach the display are carried over; the
// website's forms, sheets and buttons have nothing to say up here.
//
// Four sets are the glasses' own. `time.*` is the narrow form of a relative time
// — a trail column is nine cells wide, where the phone has a whole line — and
// `glasses.*` is the running commentary along the bottom of the screen, which is
// about this device and so has no counterpart on the website.

export type Language = "en" | "ja" | "zh";

type Dict = Record<string, string>;

const en: Dict = {
  "common.loading": "Loading",
  "clock.title": "Time",
  "clock.timezone": "Time zone",
  "clock.sunrise": "Sunrise",
  "clock.sunset": "Sunset",
  "clock.offset": "UTC{{offset}}",
  "weather.title": "Weather",
  "weather.feelsLike": "Feels like",
  "weather.humidity": "Humidity",
  "weather.wind": "Wind",
  "weather.unavailable": "Weather is unavailable right now",
  "location.title": "Here",
  "location.accuracy": "Accuracy",
  "location.stale": "Last known position",
  "location.locating": "Locating",
  "people.short": "People",
  "people.you": "you",
  "posts.nearby": "Nearby posts",
  "posts.empty": "No posts around here yet",
  "news.title": "News",
  "news.local": "Local",
  "news.places": "Around you",
  "news.empty": "Nothing to report around here",
  "news.unavailable": "Could not reach the news service",
  "news.loading": "Reading the neighbourhood",
  "events.title": "Events",
  "events.empty": "Nothing on around here this fortnight",
  "events.unavailable": "Could not reach the events service",
  "events.loading": "Looking for what is on",
  "trends.title": "Trends",
  "trends.empty": "No search trends for here right now",
  "trends.unavailable": "Could not reach Google Trends",
  "trends.loading": "Reading Google Trends",
  "warnings.title": "Warnings",
  "warnings.empty": "Nothing in force here",
  "warnings.unavailable": "Could not reach Yahoo! 天気・災害",
  "warnings.loading": "Reading the warnings",
  "warnings.issued": "issued {{time}}",
  "warnings.level": "Level {{level}}",
  "direction.title": "Direction",
  "direction.altitude": "Altitude",
  "direction.ground": "Ground",
  "direction.speed": "Speed",
  "direction.gyroscope": "Gyroscope",
  "direction.denied": "Motion access is blocked",
  "direction.unsupported": "This device has no motion sensors",
  "direction.enable": "Turn on sensors",
  "direction.asking": "Asking",
  "direction.accuracy": "±{{degrees}}°",
  "mark.saving": "Saving",
  "mark.saved": "Marked",
  "post.posting": "Posting",
  "post.posted": "Posted",
  "warnings.severity.emergency": "Emergency warning",
  "warnings.severity.urgent": "Danger warning",
  "warnings.severity.warning": "Warning",
  "warnings.severity.advisory": "Advisory",
  "warnings.kind.rain": "Heavy rain",
  "warnings.kind.flood": "Flood",
  "warnings.kind.storm": "Storm",
  "warnings.kind.blizzard": "Snowstorm",
  "warnings.kind.heavySnow": "Heavy snow",
  "warnings.kind.waves": "High waves",
  "warnings.kind.surge": "Storm surge",
  "warnings.kind.gale": "Gale",
  "warnings.kind.galeSnow": "Gale and snow",
  "warnings.kind.thunder": "Thunderstorm",
  "warnings.kind.snowmelt": "Snowmelt",
  "warnings.kind.fog": "Dense fog",
  "warnings.kind.dry": "Dry air",
  "warnings.kind.avalanche": "Avalanche",
  "warnings.kind.lowTemperature": "Low temperature",
  "warnings.kind.frost": "Frost",
  "warnings.kind.icing": "Ice accretion",
  "warnings.kind.snowAccretion": "Snow accretion",
  "warnings.kind.landslide": "Landslide",
  "warnings.kind.tornado": "Tornado",
  "warnings.kind.recordRain": "Record rainfall",
  "warnings.kind.heat": "Heatstroke",
  "direction.point.n": "N",
  "direction.point.ne": "NE",
  "direction.point.e": "E",
  "direction.point.se": "SE",
  "direction.point.s": "S",
  "direction.point.sw": "SW",
  "direction.point.w": "W",
  "direction.point.nw": "NW",
  "weatherCode.0": "Clear sky",
  "weatherCode.1": "Mainly clear",
  "weatherCode.2": "Partly cloudy",
  "weatherCode.3": "Overcast",
  "weatherCode.45": "Fog",
  "weatherCode.48": "Rime fog",
  "weatherCode.51": "Light drizzle",
  "weatherCode.53": "Drizzle",
  "weatherCode.55": "Dense drizzle",
  "weatherCode.56": "Freezing drizzle",
  "weatherCode.57": "Dense freezing drizzle",
  "weatherCode.61": "Light rain",
  "weatherCode.63": "Rain",
  "weatherCode.65": "Heavy rain",
  "weatherCode.66": "Freezing rain",
  "weatherCode.67": "Heavy freezing rain",
  "weatherCode.71": "Light snow",
  "weatherCode.73": "Snow",
  "weatherCode.75": "Heavy snow",
  "weatherCode.77": "Snow grains",
  "weatherCode.80": "Light showers",
  "weatherCode.81": "Showers",
  "weatherCode.82": "Violent showers",
  "weatherCode.85": "Light snow showers",
  "weatherCode.86": "Heavy snow showers",
  "weatherCode.95": "Thunderstorm",
  "weatherCode.96": "Thunderstorm with hail",
  "weatherCode.99": "Severe thunderstorm with hail",
  "weatherCode.unknown": "Unknown",
  "time.now": "just now",
  "time.minutes": "{{n}}m",
  "time.hours": "{{n}}h",
  "time.days": "{{n}}d",
  "glasses.connecting": "Connecting to your phone",
  "glasses.signIn": "Sign in on your phone",
  "glasses.locating": "Reading your position",
  "glasses.noFix": "No position yet",
  "glasses.offline": "lo.gcc3.com is unreachable",
  "glasses.recording": "Recording — release to post",
  "glasses.transcribing": "Transcribing",
  "glasses.noSpeech": "Nothing heard",
  "glasses.markFailed": "Could not mark this spot",
  "glasses.postFailed": "Could not post that",
  "glasses.empty": "Nothing to show yet",
};

const ja: Dict = {
  "common.loading": "読み込み中",
  "clock.title": "時刻",
  "clock.timezone": "タイムゾーン",
  "clock.sunrise": "日の出",
  "clock.sunset": "日の入り",
  "clock.offset": "UTC{{offset}}",
  "weather.title": "天気",
  "weather.feelsLike": "体感",
  "weather.humidity": "湿度",
  "weather.wind": "風速",
  "weather.unavailable": "天気を取得できません",
  "location.title": "現在地",
  "location.accuracy": "精度",
  "location.stale": "最後に確認した位置",
  "location.locating": "測位中",
  "people.short": "近くの人",
  "people.you": "自分",
  "posts.nearby": "近くの posts",
  "posts.empty": "近くにまだ post はありません",
  "news.title": "ニュース",
  "news.local": "地元",
  "news.places": "あなたの周り",
  "news.empty": "この辺りに伝えることはありません",
  "news.unavailable": "ニュースサービスに接続できません",
  "news.loading": "周辺を読み込み中",
  "events.title": "イベント",
  "events.empty": "この2週間、この辺りに開催情報はありません",
  "events.unavailable": "イベント情報に接続できません",
  "events.loading": "イベントを探しています",
  "trends.title": "トレンド",
  "trends.empty": "この地域の検索トレンドは今ありません",
  "trends.unavailable": "Google トレンドに接続できません",
  "trends.loading": "Google トレンドを読み込み中",
  "warnings.title": "警報・注意報",
  "warnings.empty": "発表なし",
  "warnings.unavailable": "Yahoo!天気・災害に接続できません",
  "warnings.loading": "警報を確認中",
  "warnings.issued": "{{time}}発表",
  "warnings.level": "レベル{{level}}",
  "direction.title": "方位",
  "direction.altitude": "高度",
  "direction.ground": "地表",
  "direction.speed": "速度",
  "direction.gyroscope": "ジャイロ",
  "direction.denied": "モーションセンサーがブロックされています",
  "direction.unsupported": "この端末にモーションセンサーはありません",
  "direction.enable": "センサーをオンにする",
  "direction.asking": "確認中",
  "direction.accuracy": "±{{degrees}}°",
  "mark.saving": "保存中",
  "mark.saved": "記録しました",
  "post.posting": "投稿中",
  "post.posted": "投稿しました",
  "warnings.severity.emergency": "特別警報",
  "warnings.severity.urgent": "危険警報",
  "warnings.severity.warning": "警報",
  "warnings.severity.advisory": "注意報",
  "warnings.kind.rain": "大雨",
  "warnings.kind.flood": "洪水",
  "warnings.kind.storm": "暴風",
  "warnings.kind.blizzard": "暴風雪",
  "warnings.kind.heavySnow": "大雪",
  "warnings.kind.waves": "波浪",
  "warnings.kind.surge": "高潮",
  "warnings.kind.gale": "強風",
  "warnings.kind.galeSnow": "風雪",
  "warnings.kind.thunder": "雷",
  "warnings.kind.snowmelt": "融雪",
  "warnings.kind.fog": "濃霧",
  "warnings.kind.dry": "乾燥",
  "warnings.kind.avalanche": "なだれ",
  "warnings.kind.lowTemperature": "低温",
  "warnings.kind.frost": "霜",
  "warnings.kind.icing": "着氷",
  "warnings.kind.snowAccretion": "着雪",
  "warnings.kind.landslide": "土砂災害",
  "warnings.kind.tornado": "竜巻",
  "warnings.kind.recordRain": "記録的短時間大雨",
  "warnings.kind.heat": "熱中症",
  "direction.point.n": "北",
  "direction.point.ne": "北東",
  "direction.point.e": "東",
  "direction.point.se": "南東",
  "direction.point.s": "南",
  "direction.point.sw": "南西",
  "direction.point.w": "西",
  "direction.point.nw": "北西",
  "weatherCode.0": "快晴",
  "weatherCode.1": "ほぼ快晴",
  "weatherCode.2": "一部曇り",
  "weatherCode.3": "曇り",
  "weatherCode.45": "霧",
  "weatherCode.48": "霧氷を伴う霧",
  "weatherCode.51": "弱い霧雨",
  "weatherCode.53": "霧雨",
  "weatherCode.55": "強い霧雨",
  "weatherCode.56": "着氷性の霧雨",
  "weatherCode.57": "強い着氷性の霧雨",
  "weatherCode.61": "弱い雨",
  "weatherCode.63": "雨",
  "weatherCode.65": "強い雨",
  "weatherCode.66": "着氷性の雨",
  "weatherCode.67": "強い着氷性の雨",
  "weatherCode.71": "弱い雪",
  "weatherCode.73": "雪",
  "weatherCode.75": "強い雪",
  "weatherCode.77": "霧雪",
  "weatherCode.80": "弱いにわか雨",
  "weatherCode.81": "にわか雨",
  "weatherCode.82": "激しいにわか雨",
  "weatherCode.85": "弱いにわか雪",
  "weatherCode.86": "強いにわか雪",
  "weatherCode.95": "雷雨",
  "weatherCode.96": "雹を伴う雷雨",
  "weatherCode.99": "激しい雹を伴う雷雨",
  "weatherCode.unknown": "不明",
  "time.now": "たった今",
  "time.minutes": "{{n}}分",
  "time.hours": "{{n}}時間",
  "time.days": "{{n}}日",
  "glasses.connecting": "スマートフォンに接続中",
  "glasses.signIn": "スマートフォンでサインイン",
  "glasses.locating": "位置を取得中",
  "glasses.noFix": "位置がまだありません",
  "glasses.offline": "lo.gcc3.com に接続できません",
  "glasses.recording": "録音中 — 離すと投稿",
  "glasses.transcribing": "文字起こし中",
  "glasses.noSpeech": "音声を認識できません",
  "glasses.markFailed": "この場所を記録できません",
  "glasses.postFailed": "投稿できません",
  "glasses.empty": "表示できるものがありません",
};

const zh: Dict = {
  "common.loading": "加载中",
  "clock.title": "时间",
  "clock.timezone": "时区",
  "clock.sunrise": "日出",
  "clock.sunset": "日落",
  "clock.offset": "UTC{{offset}}",
  "weather.title": "天气",
  "weather.feelsLike": "体感",
  "weather.humidity": "湿度",
  "weather.wind": "风速",
  "weather.unavailable": "暂时无法获取天气",
  "location.title": "此处",
  "location.accuracy": "精度",
  "location.stale": "上次已知位置",
  "location.locating": "定位中",
  "people.short": "附近的人",
  "people.you": "我",
  "posts.nearby": "附近的 posts",
  "posts.empty": "附近还没有 post",
  "news.title": "新闻",
  "news.local": "本地",
  "news.places": "你的周边",
  "news.empty": "附近暂无可报道的内容",
  "news.unavailable": "无法连接新闻服务",
  "news.loading": "正在读取周边",
  "events.title": "活动",
  "events.empty": "近两周附近暂无活动",
  "events.unavailable": "无法连接活动服务",
  "events.loading": "正在查找活动",
  "trends.title": "趋势",
  "trends.empty": "此地暂无搜索趋势",
  "trends.unavailable": "无法连接 Google 趋势",
  "trends.loading": "正在读取 Google 趋势",
  "warnings.title": "预警",
  "warnings.empty": "此地暂无预警",
  "warnings.unavailable": "无法连接 Yahoo! 天気・災害",
  "warnings.loading": "正在读取预警",
  "warnings.issued": "{{time}}发布",
  "warnings.level": "等级{{level}}",
  "direction.title": "方位",
  "direction.altitude": "高度",
  "direction.ground": "地面",
  "direction.speed": "速度",
  "direction.gyroscope": "陀螺仪",
  "direction.denied": "运动传感器已被阻止",
  "direction.unsupported": "此设备没有运动传感器",
  "direction.enable": "打开传感器",
  "direction.asking": "请求中",
  "direction.accuracy": "±{{degrees}}°",
  "mark.saving": "保存中",
  "mark.saved": "已记录",
  "post.posting": "发布中",
  "post.posted": "已发布",
  "warnings.severity.emergency": "特别警报",
  "warnings.severity.urgent": "危险警报",
  "warnings.severity.warning": "警报",
  "warnings.severity.advisory": "注意报",
  "warnings.kind.rain": "暴雨",
  "warnings.kind.flood": "洪水",
  "warnings.kind.storm": "暴风",
  "warnings.kind.blizzard": "暴风雪",
  "warnings.kind.heavySnow": "大雪",
  "warnings.kind.waves": "大浪",
  "warnings.kind.surge": "风暴潮",
  "warnings.kind.gale": "大风",
  "warnings.kind.galeSnow": "风雪",
  "warnings.kind.thunder": "雷电",
  "warnings.kind.snowmelt": "融雪",
  "warnings.kind.fog": "浓雾",
  "warnings.kind.dry": "干燥",
  "warnings.kind.avalanche": "雪崩",
  "warnings.kind.lowTemperature": "低温",
  "warnings.kind.frost": "霜冻",
  "warnings.kind.icing": "结冰",
  "warnings.kind.snowAccretion": "积雪",
  "warnings.kind.landslide": "泥石流",
  "warnings.kind.tornado": "龙卷风",
  "warnings.kind.recordRain": "短时强降雨",
  "warnings.kind.heat": "中暑",
  "direction.point.n": "北",
  "direction.point.ne": "东北",
  "direction.point.e": "东",
  "direction.point.se": "东南",
  "direction.point.s": "南",
  "direction.point.sw": "西南",
  "direction.point.w": "西",
  "direction.point.nw": "西北",
  "weatherCode.0": "晴朗",
  "weatherCode.1": "大部晴朗",
  "weatherCode.2": "多云",
  "weatherCode.3": "阴天",
  "weatherCode.45": "雾",
  "weatherCode.48": "雾凇",
  "weatherCode.51": "小毛毛雨",
  "weatherCode.53": "毛毛雨",
  "weatherCode.55": "大毛毛雨",
  "weatherCode.56": "冻毛毛雨",
  "weatherCode.57": "强冻毛毛雨",
  "weatherCode.61": "小雨",
  "weatherCode.63": "中雨",
  "weatherCode.65": "大雨",
  "weatherCode.66": "冻雨",
  "weatherCode.67": "强冻雨",
  "weatherCode.71": "小雪",
  "weatherCode.73": "中雪",
  "weatherCode.75": "大雪",
  "weatherCode.77": "米雪",
  "weatherCode.80": "小阵雨",
  "weatherCode.81": "阵雨",
  "weatherCode.82": "强阵雨",
  "weatherCode.85": "小阵雪",
  "weatherCode.86": "大阵雪",
  "weatherCode.95": "雷暴",
  "weatherCode.96": "雷暴伴冰雹",
  "weatherCode.99": "强雷暴伴冰雹",
  "weatherCode.unknown": "未知",
  "time.now": "刚刚",
  "time.minutes": "{{n}}分钟",
  "time.hours": "{{n}}小时",
  "time.days": "{{n}}天",
  "glasses.connecting": "正在连接手机",
  "glasses.signIn": "请在手机上登录",
  "glasses.locating": "正在读取位置",
  "glasses.noFix": "尚无位置",
  "glasses.offline": "无法连接 lo.gcc3.com",
  "glasses.recording": "录音中 — 松开发布",
  "glasses.transcribing": "正在转写",
  "glasses.noSpeech": "没有听到内容",
  "glasses.markFailed": "无法记录此处",
  "glasses.postFailed": "无法发布",
  "glasses.empty": "暂无内容",
};

const DICTS: Record<Language, Dict> = { en, ja, zh };

/**
 * A key, and whatever has to be dropped into it. Missing keys come back as
 * themselves rather than as an empty line: a screen reading `weather.humidity`
 * is plainly a bug, where a blank row is just a card that looks broken.
 */
export type Translate = (key: string, vars?: Record<string, string | number>) => string;

export function translator(language: Language): Translate {
  const dict = DICTS[language] ?? DICTS.en;
  return (key, vars) => {
    const template = dict[key] ?? DICTS.en[key] ?? key;
    if (!vars) return template;
    return template.replace(/\{\{(\w+)\}\}/g, (whole, name: string) =>
      name in vars ? String(vars[name]) : whole,
    );
  };
}

/** The words for a WMO weather code, by the table lo keys them under. */
export function weatherLabelKey(code: number | null | undefined): string {
  return code != null && `weatherCode.${code}` in DICTS.en ? `weatherCode.${code}` : "weatherCode.unknown";
}
